spring:
  datasource:
    url: jdbc:mysql://localhost:3306/corona
    username: testUser
    password: test!123123

  jpa:
    hibernate:
      ddl-auto: update

    # sql을 보여줌
    show-sql: true

    # sql format pretty
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  cache:
    ehcache:
      config: classpath:ehcache.xml

  # 정의 되지 않은 필드 마샬링 시, 에러발생.(컨트롤러 data binding의 경우 400리턴)
  jackson:
    deserialization:
      fail-on-unknown-properties: true