spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:corona
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    # sql을 보여줌
    show-sql: true

    # sql format pretty
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  cache:
    ehcache:
      config: classpath:ehcache.xml

  # 정의 되지 않은 필드 마샬링 시, 에러발생.(컨트롤러 data binding의 경우 400리턴)
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: 1ms

server:
  error:
    whitelabel:
      enabled: true


logging:
  level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE